monolog:
  channels: [ 'upgrade',  'install', 'auth' ]
  handlers:
    upgrade:
      type: stream
      path: "%kernel.project_dir%/logs/upgrade.log"
      level: debug
      channels: [ "upgrade" ]
    install:
      type: stream
      path: "%kernel.project_dir%/logs/install.log"
      level: debug
      channels: [ "install" ]
    auth:
      type: stream
      path: "%kernel.project_dir%/logs/auth.log"
      level: debug
      channels: [ "auth" ]
when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      nested:
        type: stream
        path: php://stderr
        level: debug
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
