security:
    enable_authenticator_manager: true
    password_hashers:
      App\Module\Users\Entity\User:
        id: App\Security\LegacyPasswordEncoder
      app_hasher:
        id: 'App\Security\LegacyPasswordHasher'

    providers:
      app_user_provider:
        entity:
          class: App\Module\Users\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true

